workspace(name = "external_data_pkg_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "9f9f3b300a9264e4c77999312ce663be5dee9a56e361a1f6fe7ec60e1beef9a3",
    strip_prefix = "rules_python-1.4.1",
    url = "https://github.com/bazel-contrib/rules_python/releases/download/1.4.1/rules_python-1.4.1.tar.gz",
)

register_toolchains("//:py_toolchain")

load("//:drake_path.bzl", "get_drake_path")

local_repository(
    name = "bazel_external_data_pkg",
    path = get_drake_path(__workspace_dir__),
)

load("//:repo_example.bzl", "add_repo_archive_repository")

add_repo_archive_repository()
